version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: melisa
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: melisa

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 8081:80
    volumes:
      - ./nginx-2.conf:/etc/nginx/nginx.conf

volumes:
  mysql_data:
