version: '3.8'

services:
  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: your_mysql_root_password
      MYSQL_DATABASE: your_mysql_database
      MYSQL_USER: your_mysql_user
      MYSQL_PASSWORD: your_mysql_password
    volumes:
      - mysql_data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    restart: always
    depends_on:
      - mysql
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: your_mysql_root_password

  tomcat:
    image: tomcat:9
    restart: always
    volumes:
      - tomcat_data:/usr/local/tomcat/webapps
      - tomcat_conf:/usr/local/tomcat/conf

  nginx:
    image: nginx:latest
    restart: always
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - tomcat_data:/usr/share/nginx/html

volumes:
  mysql_data:
  tomcat_data:
  tomcat_conf:
